part of 'scene_pipeline_models.dart';

// ---------------------------------------------------------------------------
// Scene director structured plan
// ---------------------------------------------------------------------------

/// Pacing hint for a scene.
enum ScenePacing { slow, medium, fast }

/// Per-character direction note generated by the scene director.
class DirectorCharacterNote {
  const DirectorCharacterNote({
    required this.characterId,
    required this.name,
    this.motivation = '',
    this.emotionalArc = '',
    this.keyAction = '',
  });

  final String characterId;
  final String name;
  final String motivation;
  final String emotionalArc;
  final String keyAction;
}

/// Structured representation of the director's 4-line plan plus metadata.
class SceneDirectorPlan {
  SceneDirectorPlan({
    required this.target,
    required this.conflict,
    required this.progression,
    required this.constraints,
    this.tone = '',
    this.pacing = ScenePacing.medium,
    List<DirectorCharacterNote> characterNotes = const [],
  }) : characterNotes = _immutableList(characterNotes);

  final String target;
  final String conflict;
  final String progression;
  final String constraints;
  final String tone;
  final ScenePacing pacing;
  final List<DirectorCharacterNote> characterNotes;

  /// Reconstruct the standard 4-line text format.
  String toText() {
    final l = StoryPromptTemplates.locale;
    return [
      '${l.targetLabel}${l.colon}$target',
      '${l.conflictLabel}${l.colon}$conflict',
      '${l.progressionLabel}${l.colon}$progression',
      '${l.constraintLabel}${l.colon}$constraints',
    ].join('\n');
  }

  /// Find the direction note for [characterId], if any.
  DirectorCharacterNote? noteFor(String characterId) {
    for (final note in characterNotes) {
      if (note.characterId == characterId) return note;
    }
    return null;
  }

  /// Parse from the standard 4-line format. Returns `null` if the format
  /// doesn't match.
  static SceneDirectorPlan? tryParse(String text) {
    final l = StoryPromptTemplates.locale;
    final targetPrefix = '${l.targetLabel}${l.colon}';
    final conflictPrefix = '${l.conflictLabel}${l.colon}';
    final progressionPrefix = '${l.progressionLabel}${l.colon}';
    final constraintPrefix = '${l.constraintLabel}${l.colon}';
    final lines = text
        .split('\n')
        .map((s) => s.trim())
        .where((s) => s.isNotEmpty)
        .toList(growable: false);
    if (lines.length < 4) return null;
    if (!lines[0].startsWith(targetPrefix)) return null;
    if (!lines[1].startsWith(conflictPrefix)) return null;
    if (!lines[2].startsWith(progressionPrefix)) return null;
    if (!lines[3].startsWith(constraintPrefix)) return null;
    return SceneDirectorPlan(
      target: lines[0].substring(targetPrefix.length),
      conflict: lines[1].substring(conflictPrefix.length),
      progression: lines[2].substring(progressionPrefix.length),
      constraints: lines[3].substring(constraintPrefix.length),
    );
  }
}
